{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.nextftc.nextrunner",
    "module": "ftc",
    "version": "2.0.0-BETA-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "dev.nextftc.nextrunner",
          "module": "core",
          "version": {
            "requires": "2.0.0-BETA-1"
          }
        },
        {
          "group": "dev.nextftc.nextrunner",
          "module": "actions",
          "version": {
            "requires": "2.0.0-BETA-1"
          }
        },
        {
          "group": "com.acmerobotics.dashboard",
          "module": "core",
          "version": {
            "requires": "0.4.10"
          }
        },
        {
          "group": "com.acmerobotics.dashboard",
          "module": "dashboard",
          "version": {
            "requires": "0.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-2.0.0-BETA-1.aar",
          "url": "ftc-2.0.0-BETA-1.aar",
          "size": 1296892,
          "sha512": "730b811ec9db5f90812bc657b739bd9a2ed3fdd5cf39d05d7f2baf9a0f817b89b34c4fee07fdcd19de79fffc1473a916f151b689d5c7aa5b1afff5aa6ba3b6a8",
          "sha256": "0109037dfa8eabcb26a39cf6194a0a5beef333ef43e95928a5cfe62086d4939f",
          "sha1": "43a548f520b8dfeda3693d9bf3622652ef0125fa",
          "md5": "526f2c6e0f9ddfa275f599481d3bc6bf"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.firstinspires.ftc",
          "module": "FtcCommon",
          "version": {
            "requires": "10.0.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotCore",
          "version": {
            "requires": "10.0.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Hardware",
          "version": {
            "requires": "10.0.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.12.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "dev.nextftc.nextrunner",
          "module": "core",
          "version": {
            "requires": "2.0.0-BETA-1"
          }
        },
        {
          "group": "dev.nextftc.nextrunner",
          "module": "actions",
          "version": {
            "requires": "2.0.0-BETA-1"
          }
        },
        {
          "group": "com.acmerobotics.dashboard",
          "module": "core",
          "version": {
            "requires": "0.4.10"
          }
        },
        {
          "group": "com.acmerobotics.dashboard",
          "module": "dashboard",
          "version": {
            "requires": "0.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-2.0.0-BETA-1.aar",
          "url": "ftc-2.0.0-BETA-1.aar",
          "size": 1296892,
          "sha512": "730b811ec9db5f90812bc657b739bd9a2ed3fdd5cf39d05d7f2baf9a0f817b89b34c4fee07fdcd19de79fffc1473a916f151b689d5c7aa5b1afff5aa6ba3b6a8",
          "sha256": "0109037dfa8eabcb26a39cf6194a0a5beef333ef43e95928a5cfe62086d4939f",
          "sha1": "43a548f520b8dfeda3693d9bf3622652ef0125fa",
          "md5": "526f2c6e0f9ddfa275f599481d3bc6bf"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ftc-2.0.0-BETA-1-sources.jar",
          "url": "ftc-2.0.0-BETA-1-sources.jar",
          "size": 46361,
          "sha512": "a3f52589678fedda0dfa3bebbe2fdd8d4bfa5af1634950f3fc63db25609f2d4bfb0c0e4c514dc0470b86c51f3aebd48ba33b4b22bbf6a0c68c21a17c56e1b68b",
          "sha256": "d46d0f2392a84908902f52b3bc1e517a391a737c8ca6074d623f7dd4f1d0c3b3",
          "sha1": "f387cd84d0b0c9c368e012ec18fa3277ccd0299b",
          "md5": "27dc29e9004db40bbcb9968c702a5748"
        }
      ]
    }
  ]
}
