{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.nextftc.nextrunner",
    "module": "ftc",
    "version": "2.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "dev.nextftc.nextrunner",
          "module": "core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "dev.nextftc.nextrunner",
          "module": "actions",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.acmerobotics.dashboard",
          "module": "core",
          "version": {
            "requires": "0.4.10"
          }
        },
        {
          "group": "com.acmerobotics.dashboard",
          "module": "dashboard",
          "version": {
            "requires": "0.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-2.1.1.aar",
          "url": "ftc-2.1.1.aar",
          "size": 1286627,
          "sha512": "c3808ee92aed458962c526fb3b2113a6321b2c34b0cfabb95cca2c37a3633d545673a3615ebbf7b65d7aab11f3f7d7487541c37f2c73c6642fef79f7f30a8726",
          "sha256": "8ac11646ab634e0da7443831324a411096b6a9d857bb7e85c5b5bbcd599dcf8e",
          "sha1": "9bf10be63eb53e00459952c2f1d34e8706871996",
          "md5": "f8d6b32acb7fdafcc4e69cc8681a21e8"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.firstinspires.ftc",
          "module": "FtcCommon",
          "version": {
            "requires": "10.0.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotCore",
          "version": {
            "requires": "10.0.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Hardware",
          "version": {
            "requires": "10.0.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.12.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "dev.nextftc.nextrunner",
          "module": "core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "dev.nextftc.nextrunner",
          "module": "actions",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.acmerobotics.dashboard",
          "module": "core",
          "version": {
            "requires": "0.4.10"
          }
        },
        {
          "group": "com.acmerobotics.dashboard",
          "module": "dashboard",
          "version": {
            "requires": "0.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-2.1.1.aar",
          "url": "ftc-2.1.1.aar",
          "size": 1286627,
          "sha512": "c3808ee92aed458962c526fb3b2113a6321b2c34b0cfabb95cca2c37a3633d545673a3615ebbf7b65d7aab11f3f7d7487541c37f2c73c6642fef79f7f30a8726",
          "sha256": "8ac11646ab634e0da7443831324a411096b6a9d857bb7e85c5b5bbcd599dcf8e",
          "sha1": "9bf10be63eb53e00459952c2f1d34e8706871996",
          "md5": "f8d6b32acb7fdafcc4e69cc8681a21e8"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ftc-2.1.1-sources.jar",
          "url": "ftc-2.1.1-sources.jar",
          "size": 44701,
          "sha512": "5fae8308675e1d2d70380abbb0ae64c3c825c1939060555b19d58e496e5c865c76c5c6ff924c40b77fd07bc64f07472be61c1d2819e56a52414b977005ffae66",
          "sha256": "49074c700f4abdfdb5d51cb1ae72951abd1287c3b055a4785118eeec138e2974",
          "sha1": "59615b9db4b6d1f019a0aeff0a76a091dafb9f33",
          "md5": "0f437953762dabb73a3ec6ec3bca6de8"
        }
      ]
    }
  ]
}
