{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.nextftc.nextrunner",
    "module": "ftc",
    "version": "2.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "dev.nextftc.nextrunner",
          "module": "core",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "dev.nextftc.nextrunner",
          "module": "actions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-2.2.0.aar",
          "url": "ftc-2.2.0.aar",
          "size": 507507,
          "sha512": "deaf23fe34258eac0c5b9ee6e630320f2e33fe52474cd5f7e218eb5f2c376f9df3f2b5e7f1f10f2fa8c8665ad1a13e0bfb4ef9dce8245c98e6f53def712cca6e",
          "sha256": "5867b1d376d8a6068e4c3b6b3763dcdb4f39905d2fd4fe79e55d07a4268d9c99",
          "sha1": "a2fcb55d9d3a38e38f77d0eefd38ff06f2cebf03",
          "md5": "cd351f4b49daf913a4fa0b04c8f05eaa"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.acmerobotics.dashboard",
          "module": "core",
          "version": {
            "requires": "0.4.10"
          }
        },
        {
          "group": "com.acmerobotics.dashboard",
          "module": "dashboard",
          "version": {
            "requires": "0.4.10"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "FtcCommon",
          "version": {
            "requires": "10.0.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotCore",
          "version": {
            "requires": "10.0.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Hardware",
          "version": {
            "requires": "10.0.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.12.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "dev.nextftc.nextrunner",
          "module": "core",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "dev.nextftc.nextrunner",
          "module": "actions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-2.2.0.aar",
          "url": "ftc-2.2.0.aar",
          "size": 507507,
          "sha512": "deaf23fe34258eac0c5b9ee6e630320f2e33fe52474cd5f7e218eb5f2c376f9df3f2b5e7f1f10f2fa8c8665ad1a13e0bfb4ef9dce8245c98e6f53def712cca6e",
          "sha256": "5867b1d376d8a6068e4c3b6b3763dcdb4f39905d2fd4fe79e55d07a4268d9c99",
          "sha1": "a2fcb55d9d3a38e38f77d0eefd38ff06f2cebf03",
          "md5": "cd351f4b49daf913a4fa0b04c8f05eaa"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ftc-2.2.0-sources.jar",
          "url": "ftc-2.2.0-sources.jar",
          "size": 44701,
          "sha512": "5fae8308675e1d2d70380abbb0ae64c3c825c1939060555b19d58e496e5c865c76c5c6ff924c40b77fd07bc64f07472be61c1d2819e56a52414b977005ffae66",
          "sha256": "49074c700f4abdfdb5d51cb1ae72951abd1287c3b055a4785118eeec138e2974",
          "sha1": "59615b9db4b6d1f019a0aeff0a76a091dafb9f33",
          "md5": "0f437953762dabb73a3ec6ec3bca6de8"
        }
      ]
    }
  ]
}
