{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.nextftc.nextrunner",
    "module": "ftc",
    "version": "2.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "dev.nextftc.nextrunner",
          "module": "core",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "dev.nextftc.nextrunner",
          "module": "actions",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-2.2.1.aar",
          "url": "ftc-2.2.1.aar",
          "size": 507693,
          "sha512": "22d624e22bc4899a8e3a450b7af8434341dd7c96231b8f1dcb4199bc482cc6ab5305001b02e2456a6e9f99bbba19c0f605938c097ab13fc4474dcd414d2fcc47",
          "sha256": "820a676f8d741159d7d346551ddfe09692b911e34c5bd196f70426798f541d6c",
          "sha1": "53692243f8e8930eea162a5f201e04778b9c8412",
          "md5": "eca4d31742b0fc894d0f9d395c48a0cf"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.acmerobotics.dashboard",
          "module": "core",
          "version": {
            "requires": "0.4.10"
          }
        },
        {
          "group": "com.acmerobotics.dashboard",
          "module": "dashboard",
          "version": {
            "requires": "0.4.10"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "FtcCommon",
          "version": {
            "requires": "10.0.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotCore",
          "version": {
            "requires": "10.0.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Hardware",
          "version": {
            "requires": "10.0.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.12.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "dev.nextftc.nextrunner",
          "module": "core",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "dev.nextftc.nextrunner",
          "module": "actions",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-2.2.1.aar",
          "url": "ftc-2.2.1.aar",
          "size": 507693,
          "sha512": "22d624e22bc4899a8e3a450b7af8434341dd7c96231b8f1dcb4199bc482cc6ab5305001b02e2456a6e9f99bbba19c0f605938c097ab13fc4474dcd414d2fcc47",
          "sha256": "820a676f8d741159d7d346551ddfe09692b911e34c5bd196f70426798f541d6c",
          "sha1": "53692243f8e8930eea162a5f201e04778b9c8412",
          "md5": "eca4d31742b0fc894d0f9d395c48a0cf"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ftc-2.2.1-sources.jar",
          "url": "ftc-2.2.1-sources.jar",
          "size": 44751,
          "sha512": "b574a8a3bd6f048309955082a263288659267f06cf3697a5a2dcc8a187ed1fa2bfcc20c5fa35f15fefaeee4787dc7926c51e7dcd61eee964a7f0125a29666d6e",
          "sha256": "c4c8693a3a79a4f2d056dea9dd42c657c4e384a7fd75420db2cf17b37bf7b283",
          "sha1": "635700225ead4f28de54e371e857d100709ee1aa",
          "md5": "b69ddf46ab599b89a33f1eff90c1785a"
        }
      ]
    }
  ]
}
